// <auto-generated />
using HRSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

#nullable disable

namespace HRSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class HrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ---------------- Role ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.Role", b =>
            {
                b.Property<int>("RoleId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Description").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("RoleId");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Roles");
            });

            // ---------------- Department ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.Department", b =>
            {
                b.Property<int>("DepartmentId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));
                b.Property<string>("Code").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int?>("ManagerUserId").HasColumnType("int");
                b.HasKey("DepartmentId");
                b.HasIndex("Code").IsUnique();
                b.HasIndex("ManagerUserId");
                b.ToTable("Departments");
            });

            // ---------------- Employee ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.Employee", b =>
            {
                b.Property<int>("EmployeeId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));
                b.Property<string>("EmployeeNo").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("DepartmentId").HasColumnType("int");
                b.Property<string>("Position").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<byte>("Status").ValueGeneratedOnAdd().HasColumnType("tinyint").HasDefaultValue((byte)0);
                b.Property<DateTime?>("HireDate").HasColumnType("date");
                b.Property<DateTime?>("ResignDate").HasColumnType("date");
                b.Property<bool>("IsDeleted").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(false);
                b.HasKey("EmployeeId");
                b.HasIndex("EmployeeNo").IsUnique();
                b.HasIndex("DepartmentId");
                b.ToTable("Employees");
            });

            // ---------------- AppUser ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.AppUser", b =>
            {
                b.Property<int>("UserId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));
                b.Property<string>("UserName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(true);
                b.Property<int?>("EmployeeId").HasColumnType("int");
                b.Property<DateTime>("CreatedAt").ValueGeneratedOnAdd().HasColumnType("datetime2")
                    .HasDefaultValueSql("SYSUTCDATETIME()");
                b.HasKey("UserId");
                b.HasIndex("UserName").IsUnique();
                b.HasIndex("Email").IsUnique();
                b.HasIndex("EmployeeId").IsUnique().HasFilter("[EmployeeId] IS NOT NULL");
                b.ToTable("AppUsers");
            });

            // ---------------- UserRole ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.UserRole", b =>
            {
                b.Property<int>("UserId").HasColumnType("int");
                b.Property<int>("RoleId").HasColumnType("int");
                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId");
                b.ToTable("UserRoles");
            });

            // ---------------- AccountType ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.AccountType", b =>
            {
                b.Property<int>("AccountTypeId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountTypeId"));
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<int>("RespDepartmentId").HasColumnType("int");
                b.Property<string>("Description").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(true);
                b.HasKey("AccountTypeId");
                b.HasIndex("RespDepartmentId");
                b.ToTable("AccountTypes");
            });

            // ---------------- AccountRequest ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.AccountRequest", b =>
            {
                b.Property<int>("RequestId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));
                b.Property<int>("EmployeeId").HasColumnType("int");
                b.Property<byte>("RequestType").HasColumnType("tinyint");
                b.Property<byte>("Status").ValueGeneratedOnAdd().HasColumnType("tinyint").HasDefaultValue((byte)0);
                b.Property<int>("CreatedByUserId").HasColumnType("int");
                b.Property<string>("Remark").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime?>("SubmittedAt").HasColumnType("datetime2");
                b.Property<DateTime?>("CompletedAt").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").ValueGeneratedOnAdd().HasColumnType("datetime2")
                    .HasDefaultValueSql("SYSUTCDATETIME()");
                b.Property<byte[]>("RowVersion").IsConcurrencyToken().ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");
                b.HasKey("RequestId");
                b.HasIndex("EmployeeId");
                b.HasIndex("CreatedByUserId");
                b.HasIndex("Status");
                b.ToTable("AccountRequests");
            });

            // ---------------- AccountRequestItem ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.AccountRequestItem", b =>
            {
                b.Property<int>("ItemId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));
                b.Property<int>("RequestId").HasColumnType("int");
                b.Property<int>("AccountTypeId").HasColumnType("int");
                b.Property<byte>("Action").HasColumnType("tinyint");
                b.Property<byte>("Status").ValueGeneratedOnAdd().HasColumnType("tinyint").HasDefaultValue((byte)0);
                b.Property<int?>("HandledByUserId").HasColumnType("int");
                b.Property<DateTime?>("HandledAt").HasColumnType("datetime2");
                b.Property<string>("Remark").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.HasKey("ItemId");
                b.HasIndex("RequestId");
                b.HasIndex("AccountTypeId");
                b.HasIndex("HandledByUserId");
                b.HasIndex("RequestId", "AccountTypeId").IsUnique().HasDatabaseName("UX_AccountRequestItems_Request_Type");
                b.ToTable("AccountRequestItems");
            });

            // ---------------- EmployeeAccount ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.EmployeeAccount", b =>
            {
                b.Property<int>("AccountId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));
                b.Property<int>("EmployeeId").HasColumnType("int");
                b.Property<int>("AccountTypeId").HasColumnType("int");
                b.Property<string>("AccountIdentifier").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<byte>("Status").ValueGeneratedOnAdd().HasColumnType("tinyint").HasDefaultValue((byte)0);
                b.Property<DateTime?>("ActivatedAt").HasColumnType("datetime2");
                b.Property<DateTime?>("DeactivatedAt").HasColumnType("datetime2");
                b.HasKey("AccountId");
                b.HasIndex("EmployeeId");
                b.HasIndex("AccountTypeId");
                b.ToTable("EmployeeAccounts");
            });

            // ---------------- Attachment ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.Attachment", b =>
            {
                b.Property<int>("AttachmentId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));
                b.Property<int>("RequestId").HasColumnType("int");
                b.Property<string>("FileName").IsRequired().HasMaxLength(260).HasColumnType("nvarchar(260)");
                b.Property<string>("FilePath").IsRequired().HasMaxLength(1024).HasColumnType("nvarchar(1024)");
                b.Property<string>("ContentType").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<long>("FileSize").ValueGeneratedOnAdd().HasColumnType("bigint").HasDefaultValue(0L);
                b.Property<DateTime>("UploadedAt").ValueGeneratedOnAdd().HasColumnType("datetime2")
                    .HasDefaultValueSql("SYSUTCDATETIME()");
                b.HasKey("AttachmentId");
                b.HasIndex("RequestId");
                b.ToTable("Attachments");
            });

            // ---------------- Notification ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.Notification", b =>
            {
                b.Property<int>("NotificationId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));
                b.Property<int>("RequestId").HasColumnType("int");
                b.Property<string>("ToAddress").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("Subject").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<byte>("Type").HasColumnType("tinyint");
                b.Property<byte>("Status").ValueGeneratedOnAdd().HasColumnType("tinyint").HasDefaultValue((byte)0);
                b.Property<DateTime?>("SentAt").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").ValueGeneratedOnAdd().HasColumnType("datetime2")
                    .HasDefaultValueSql("SYSUTCDATETIME()");
                b.HasKey("NotificationId");
                b.HasIndex("RequestId");
                b.ToTable("Notifications");
            });

            // ---------------- AuditLog ----------------
            modelBuilder.Entity("HRSystem.Domain.Entities.AuditLog", b =>
            {
                b.Property<long>("AuditId").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));
                b.Property<int?>("UserId").HasColumnType("int");
                b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("EntityName").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("EntityId").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Detail").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("Timestamp").ValueGeneratedOnAdd().HasColumnType("datetime2")
                    .HasDefaultValueSql("SYSUTCDATETIME()");
                b.HasKey("AuditId");
                b.HasIndex("UserId");
                b.HasIndex("Timestamp");
                b.ToTable("AuditLogs");
            });

            // ======================= Relationships =======================
            modelBuilder.Entity("HRSystem.Domain.Entities.Employee", b =>
            {
                b.HasOne("HRSystem.Domain.Entities.Department", "Department")
                    .WithMany("Employees").HasForeignKey("DepartmentId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Department");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.AppUser", b =>
            {
                b.HasOne("HRSystem.Domain.Entities.Employee", "Employee")
                    .WithOne("AppUser").HasForeignKey("HRSystem.Domain.Entities.AppUser", "EmployeeId")
                    .OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Employee");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.Department", b =>
            {
                b.HasOne("HRSystem.Domain.Entities.AppUser", "Manager")
                    .WithMany().HasForeignKey("ManagerUserId")
                    .OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Manager");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.UserRole", b =>
            {
                b.HasOne("HRSystem.Domain.Entities.AppUser", "User")
                    .WithMany("UserRoles").HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("HRSystem.Domain.Entities.Role", "Role")
                    .WithMany("UserRoles").HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
                b.Navigation("Role");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.AccountType", b =>
            {
                b.HasOne("HRSystem.Domain.Entities.Department", "RespDepartment")
                    .WithMany("AccountTypes").HasForeignKey("RespDepartmentId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("RespDepartment");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.AccountRequest", b =>
            {
                b.HasOne("HRSystem.Domain.Entities.Employee", "Employee")
                    .WithMany("AccountRequests").HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("HRSystem.Domain.Entities.AppUser", "CreatedByUser")
                    .WithMany().HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Employee");
                b.Navigation("CreatedByUser");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.AccountRequestItem", b =>
            {
                b.HasOne("HRSystem.Domain.Entities.AccountRequest", "Request")
                    .WithMany("Items").HasForeignKey("RequestId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("HRSystem.Domain.Entities.AccountType", "AccountType")
                    .WithMany().HasForeignKey("AccountTypeId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("HRSystem.Domain.Entities.AppUser", "HandledByUser")
                    .WithMany().HasForeignKey("HandledByUserId")
                    .OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Request");
                b.Navigation("AccountType");
                b.Navigation("HandledByUser");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.EmployeeAccount", b =>
            {
                b.HasOne("HRSystem.Domain.Entities.Employee", "Employee")
                    .WithMany("Accounts").HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("HRSystem.Domain.Entities.AccountType", "AccountType")
                    .WithMany().HasForeignKey("AccountTypeId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Employee");
                b.Navigation("AccountType");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.Attachment", b =>
            {
                b.HasOne("HRSystem.Domain.Entities.AccountRequest", "Request")
                    .WithMany("Attachments").HasForeignKey("RequestId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Request");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.Notification", b =>
            {
                b.HasOne("HRSystem.Domain.Entities.AccountRequest", "Request")
                    .WithMany("Notifications").HasForeignKey("RequestId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Request");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.AuditLog", b =>
            {
                b.HasOne("HRSystem.Domain.Entities.AppUser", "User")
                    .WithMany().HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("User");
            });

            // ======================= Navigations =======================
            modelBuilder.Entity("HRSystem.Domain.Entities.Department", b =>
            {
                b.Navigation("AccountTypes");
                b.Navigation("Employees");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.Role", b => b.Navigation("UserRoles"));

            modelBuilder.Entity("HRSystem.Domain.Entities.Employee", b =>
            {
                b.Navigation("AccountRequests");
                b.Navigation("Accounts");
                b.Navigation("AppUser");
            });

            modelBuilder.Entity("HRSystem.Domain.Entities.AppUser", b => b.Navigation("UserRoles"));

            modelBuilder.Entity("HRSystem.Domain.Entities.AccountRequest", b =>
            {
                b.Navigation("Attachments");
                b.Navigation("Items");
                b.Navigation("Notifications");
            });
#pragma warning restore 612, 618
        }
    }
}
